// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX6Y8qnPuFJyVgLhm-_4CQj5pp130H0fU',
    appId: '1:1063376164798:web:20ec9c8cc9cf3a95304bef',
    messagingSenderId: '1063376164798',
    projectId: 'kaisen-314',
    authDomain: 'kaisen-314.firebaseapp.com',
    storageBucket: 'kaisen-314.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1o1Fiy_UkKq5NWttbMfFmIPASHYwLics',
    appId: '1:1063376164798:android:eee688df90e053b9304bef',
    messagingSenderId: '1063376164798',
    projectId: 'kaisen-314',
    storageBucket: 'kaisen-314.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3iHfsEdDDrtSM4C3Xex7CiI8wtQGb4-w',
    appId: '1:1063376164798:ios:c6c15f42da67a371304bef',
    messagingSenderId: '1063376164798',
    projectId: 'kaisen-314',
    storageBucket: 'kaisen-314.firebasestorage.app',
    iosBundleId: 'com.example.kaisen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX6Y8qnPuFJyVgLhm-_4CQj5pp130H0fU',
    appId: '1:1063376164798:web:875b0d285e4a0447304bef',
    messagingSenderId: '1063376164798',
    projectId: 'kaisen-314',
    authDomain: 'kaisen-314.firebaseapp.com',
    storageBucket: 'kaisen-314.firebasestorage.app',
  );
}
